# Generated by Django 4.1.7 on 2023-03-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, null=True, unique=True, verbose_name='Гос номер')),
                ('brand', models.CharField(max_length=200, verbose_name='Марка машины')),
                ('model', models.CharField(max_length=200, verbose_name='Модел машины')),
                ('year', models.PositiveBigIntegerField(verbose_name='Год выпуска')),
                ('color', models.CharField(max_length=200, verbose_name='Цвет авто')),
                ('redder_location', models.CharField(max_length=100, verbose_name='Расположение руля')),
                ('engine_volume', models.PositiveBigIntegerField(verbose_name='Объем двигателя')),
            ],
        ),
    ]
